import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FAFAFA" },
  header: {
    backgroundColor: "#FFFFFF",
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FAFAFA",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  backText: { fontSize: 24, color: "#535FFD", fontWeight: "300", lineHeight: 24 },
  headerTitle: { fontSize: 20, fontWeight: "800", color: "#383940", textAlign: "center" },
  headerSpacer: { width: 40 },
  scrollView: { flex: 1 },
  scrollContent: { padding: 24, paddingBottom: 40 },
  introSection: { marginBottom: 30 },
  introTitle: { fontSize: 24, fontWeight: "700", color: "#383940", marginBottom: 8 },
  introSubtitle: { fontSize: 16, color: "#64748B", lineHeight: 22 },
  semesterCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  semesterHeader: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  semesterTitle: { fontSize: 18, fontWeight: "700", color: "#383940" },
  courseCount: {
    backgroundColor: "rgba(83, 95, 253, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  courseCountText: { color: "#535FFD", fontSize: 12, fontWeight: "600" },
  coursesList: { gap: 16, marginBottom: 20 },
  inputContainer: { gap: 8 },
  inputLabel: { fontSize: 14, fontWeight: "600", color: "#383940" },
  input: {
    backgroundColor: "#FAFAFA",
    borderWidth: 1,
    borderColor: "#F1F5F9",
    padding: 16,
    borderRadius: 12,
    fontSize: 16,
    color: "#383940",
  },
  addBtn: {
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#535FFD",
    borderStyle: "dashed",
  },
  addBtnText: { color: "#535FFD", fontSize: 14, fontWeight: "600" },
  finishBtn: {
    backgroundColor: "#535FFD",
    padding: 20,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 20,
    shadowColor: "#535FFD",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  finishBtnText: { color: "#FFFFFF", fontSize: 18, fontWeight: "700" },
  bottomSpacing: { height: 20 },
});